### ISSUE TITLE
Краш в измерении Spectrum

### ISSUE THREAD

**Issue by Nanachi104** [DenisMasterHerobrine/ElerionBloodNSteel#137]
Командой отправились изучать измерение под бедроком, ходили вместе, всё было нормально, в какой-то момент сервер просты выключается и уходит на перезапуск и при повторном подключение проблема не уходит, просто застряли в этом мире.

[crash-2024-08-08_17.13.54-server.txt](https://github.com/user-attachments/files/16549379/crash-2024-08-08_17.13.54-server.txt)

Я в краш репортах вообще самовар, мб кто-то сможет понять в чём проблемма.

**Comment by Nanachi104** [comment]
*Подробная информация*
Краш происходит только в биоме драконьей гнили, там появляется какой-то "первобытный огнь" который приводит к крашу. 

at de.dafuqs.spectrum.blocks.PrimordialFireBlock.trySpreadingFire(PrimordialFireBlock.java:194)

at de.dafuqs.spectrum.blocks.PrimordialFireBlock.scheduledTick(PrimordialFireBlock.java:153)

Может как-то знает, как можно его удали/отключить его появления.
У меня есть версия, что в этом биоме есть цветок, который при взрыве образует этот огонь, но что с ним не так я хз.

**Comment by DenisMasterHerobrine** [comment]
Исправлено в 0.9.5.1.
(подробнее см. в https://github.com/DaFuqs/Spectrum/issues/388)
