### ISSUE TITLE
[0.9.4.1 Server Pack] Cant startup. KubeJS

### ISSUE THREAD

**Issue by LieSain1** [DenisMasterHerobrine/ElerionBloodNSteel#72]
```
[07:39:23] [main/INFO]: Initialized color sets in 237ms
[07:39:23] [main/INFO]: Initialized color sets in 57ms
[07:39:23] [main/INFO]: Finished mod setup in: [0, 0, 0, 0, 0, 0, 0, 0, 0] ms
[07:39:23] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'kubejs'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.15.10.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launcher.jar:1.0.1]
Caused by: java.lang.RuntimeException: There were KubeJS startup script syntax errors! See logs/kubejs/startup.log for more info
	at dev.latvian.mods.kubejs.KubeJS.loadComplete(KubeJS.java:237) ~[kubejs-fabric-1902.6.2-build.63.jar:?]
	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitializeServer(KubeJSFabric.java:69) ~[kubejs-fabric-1902.6.2-build.63.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
	... 7 more
```

```
[07:33:46] [INIT] KubeJS 1902.6.2-build.63; MC 1902 fabric
[07:33:46] [INIT] Loaded plugins:
[07:33:46] [INIT] - dev.latvian.mods.kubejs.fabric.BuiltinKubeJSFabricPlugin
[07:33:46] [INIT] - dev.ftb.mods.ftbxmodcompat.ftbquests.kubejs.KubeJSIntegration
[07:33:46] [INIT] - dev.ftb.mods.ftbxmodcompat.ftbteams.kubejs.FTBTeamsKubeJSPlugin
[07:33:46] [INIT] - net.impleri.itemskills.integrations.kubejs.ItemSkillsPlugin
[07:33:46] [INIT] - dev.thestaticvoid.mi_sound_addon.compat.kubejs.MISoundAddonKubeJSPlugin
[07:33:46] [INIT] - dev.latvian.mods.kubejs.create.KubeJSCreatePlugin
[07:33:46] [INIT] - pie.ilikepiefoo.AdditionsPlugin
[07:33:46] [INIT] - pie.ilikepiefoo.fabric.FabricPlugin
[07:33:46] [INIT] - net.impleri.playerskills.integration.kubejs.PlayerSkillsPlugin
[07:33:46] [INIT] - net.impleri.blockskills.integrations.kubejs.BlockSkillsPlugin
[07:33:46] [INIT] - com.prunoideae.KubeJSBotaniaPlugin
[07:33:46] [INIT] - net.impleri.fluidskills.integrations.kubejs.FluidSkillsPlugin
[07:33:46] [INIT] - com.almostreliable.lootjs.kube.LootJSPlugin
[07:33:46] [INIT] - com.almostreliable.ponderjs.PonderJSPlugin
[07:33:46] [INIT] - aztech.modern_industrialization.compat.kubejs.MIKubeJSPlugin
[07:33:46] [INFO] Loaded script startup_scripts:statech/misc.js in 0.028 s
[07:33:46] [INFO] Loaded script startup_scripts:statech/clear_armor.js in 0.002 s
[07:33:46] [INFO] Loaded script startup_scripts:statech/coins.js in 0.0 s
[07:33:46] [INFO] Loaded script startup_scripts:statech/food.js in 0.004 s
[07:33:46] [INFO] Loaded script startup_scripts:platform_rename.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/fluids.js in 0.003 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/ebf_tiers.js in 0.0 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/machine_casing.js in 0.0 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/industrial_greenhouse.js in 0.003 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/large_chemical_reactor.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/space_probe_launcher.js in 0.002 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/large_steam_macerator.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/pyrolyse_oven.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/core_drill.js in 0.003 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/singularity_forge.js in 0.003 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/mob_crusher.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/boss_crusher.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/multiblocks/blood_generator.js in 0.002 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/machines/alloy_smelter.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/machines/rocket_part_assembler.js in 0.0 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/machines/laser_engraver.js in 0.002 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/machines/photosynthetic_chamber.js in 0.0 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/sounds.js in 0.001 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/materials.js in 0.003 s
[07:33:46] [INFO] Loaded script startup_scripts:modern_industrialization/fuels.js in 0.0 s
[07:33:46] [INFO] elerion_steel_and_bones/StartupRoleRegistryLoader.js#1: 
================================================================================
Stage Registry Loader is now registering game stages.
If the game freezes, please wait for some time, while the stages are loading.
================================================================================

[07:33:46] [INFO] Loaded script startup_scripts:elerion_steel_and_bones/StartupRoleRegistryLoader.js in 0.001 s
[07:33:46] [INFO] Loaded 26/26 KubeJS startup scripts in 0.187 s
[07:33:46] [INFO] elerion_steel_and_bones/StartupRoleRegistryLoader.js#10: Created basic skill skills:technician
[07:33:46] [INFO] elerion_steel_and_bones/StartupRoleRegistryLoader.js#16: Created basic skill skills:magician
[07:33:46] [INFO] elerion_steel_and_bones/StartupRoleRegistryLoader.js#22: Created basic skill skills:later_content
[07:33:46] [ERROR] ! Error occurred while handling event 'MIMaterialEvents.addMaterials': net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: modern_industrialization:сalorite_block
[07:33:46] [ERROR] ! net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: modern_industrialization:сalorite_block
[07:33:46] [ERROR] ! 	at net.minecraft.class_2960.<init>(class_2960.java:41)
[07:33:46] [ERROR] ! 	at net.minecraft.class_2960.<init>(class_2960.java:50)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.MIIdentifier.<init>(MIIdentifier.java:33)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.definition.Definition.<init>(Definition.java:52)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.definition.BlockDefinition.<init>(BlockDefinition.java:60)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.MIBlock.block(MIBlock.java:140)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.MIBlock.block(MIBlock.java:153)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.MIBlock.block(MIBlock.java:171)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.MIBlock.block(MIBlock.java:165)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.materials.part.PartTemplate.lambda$asBlock$3(PartTemplate.java:137)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.materials.part.PartTemplate.lambda$create$5(PartTemplate.java:218)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.materials.part.MaterialItemPartImpl.register(MaterialItemPartImpl.java:67)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.materials.MaterialBuilder.build(MaterialBuilder.java:124)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.materials.MaterialRegistry.addMaterial(MaterialRegistry.java:37)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.compat.kubejs.material.AddMaterialsEventJS.createMaterial(AddMaterialsEventJS.java:38)
[07:33:46] [ERROR] ! 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[07:33:46] [ERROR] ! 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:987)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:370)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.Context.doTopCall(Context.java:1325)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[07:33:46] [ERROR] ! 	at jdk.proxy2/jdk.proxy2.$Proxy132.onEvent(Unknown Source)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:301)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:271)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:178)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.compat.kubejs.LoadedKubeJSProxy.fireAddMaterialsEvent(LoadedKubeJSProxy.java:44)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.materials.MIMaterials.<clinit>(MIMaterials.java:746)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.ModernIndustrialization.initialize(ModernIndustrialization.java:94)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.MIStartup.initialize(MIStartup.java:42)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.MIStartup.onKubejsPluginLoaded(MIStartup.java:60)
[07:33:46] [ERROR] ! 	at aztech.modern_industrialization.compat.kubejs.MIKubeJSPlugin.initStartup(MIKubeJSPlugin.java:53)
[07:33:46] [ERROR] ! 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.java:115)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:147)
[07:33:46] [ERROR] ! 	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:22)
[07:33:46] [ERROR] ! 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
[07:33:46] [ERROR] ! 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
[07:33:46] [ERROR] ! 	at net.minecraft.server.Main.main(Main.java:101)
[07:33:46] [ERROR] ! 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[07:33:46] [ERROR] ! 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[07:33:46] [ERROR] ! 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[07:33:46] [ERROR] ! 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[07:33:46] [ERROR] ! 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)

```

Либо я дурак, либо чего то не понимаю.

**Comment by LieSain1** [comment]
Во первых попробовал сменить заглавную букву "Calorite", ибо она была заглавной

```
e.createMaterial('Calorite', 'calorite', 0xC94D4E,
        builder => {
            builder.addParts('hot_ingot', 'plate', 'gear', 'ring', 'rod', 'bolt', 'drill_head' )
                .block('iron')
                .defaultRecipes();
        });
```

Не помогло, стер напрочь этот блок. Вроде помогло :)

**Comment by DenisMasterHerobrine** [comment]
Контент из 0.9.5 частично оказался в билде для 0.9.4.1. Исправил на бусти, сервер должен запускаться и работать корректно сейчас.
